---
title: "Medical_Student_Mental_Health_Data_Analysis"
author: "George Melrose"
date: "10/07/2024"
output: 
 html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)

pacman::p_load(tidyverse,icd,knitr,kableExtra,finalfit,lubridate,data.table,
               janitor,flextable,survival,survminer,cmprsk,rmdHelpers, ggrepel,
               scales,RColorBrewer,GGally,randomForest, caret)


```


```{r loading in data}
Data_Carrard_et_al_2022_MedTeach <- read_csv("C:/Users/gam55/Downloads/archive/Data Carrard et al. 2022 MedTeach.csv")

Codebook_Carrard_et_al_2022_MedTeach <- read_csv("C:/Users/gam55/Downloads/archive/Codebook Carrard et al. 2022 MedTeach.csv")

data <- Data_Carrard_et_al_2022_MedTeach


rm(Data_Carrard_et_al_2022_MedTeach)
```

```{r formatting variables}
#Getting the curriculum year specifically#
data <- data %>%
  mutate(curriculum_year = case_when(
    year == 1 ~ "Bmed1",
    year == 2 ~ "Bmed2",
    year == 3 ~ "Bmed3",
    year == 4 ~ "Mmed1",
    year == 5 ~ "Mmed2",
    year == 6 ~ "Mmed3",
    TRUE ~ NA_character_  
  ))

#Generating a sex character column#
data <- data %>%
  mutate(sex_character = case_when(
    sex == 1 ~ "Man",
    sex == 2 ~ "Woman",
    sex == 3 ~ "Non-binary",
    TRUE ~ NA_character_
  ))

#Mapping glang values to a native language column#
data <- data %>%
  mutate(native_language = case_when(
    glang == 1 ~ "French",
    glang == 15 ~ "German",
    glang == 20 ~ "English",
    glang == 37 ~ "Arab",
    glang == 51 ~ "Basque",
    glang == 52 ~ "Bulgarian",
    glang == 53 ~ "Catalan",
    glang == 54 ~ "Chinese",
    glang == 59 ~ "Korean",
    glang == 60 ~ "Croatian",
    glang == 62 ~ "Danish",
    glang == 63 ~ "Spanish",
    glang == 82 ~ "Estonian",
    glang == 83 ~ "Finnish",
    glang == 84 ~ "Galician",
    glang == 85 ~ "Greek",
    glang == 86 ~ "Hebrew",
    glang == 87 ~ "Hindi",
    glang == 88 ~ "Hungarian",
    glang == 89 ~ "Indonesian",
    glang == 90 ~ "Italian",
    glang == 92 ~ "Japanese",
    glang == 93 ~ "Kazakh",
    glang == 94 ~ "Latvian",
    glang == 95 ~ "Lithuanian",
    glang == 96 ~ "Malay",
    glang == 98 ~ "Dutch",
    glang == 100 ~ "Norwegian",
    glang == 101 ~ "Polish",
    glang == 102 ~ "Portuguese",
    glang == 104 ~ "Romanian",
    glang == 106 ~ "Russian",
    glang == 108 ~ "Serbian",
    glang == 112 ~ "Slovak",
    glang == 113 ~ "Slovenian",
    glang == 114 ~ "Swedish",
    glang == 116 ~ "Czech",
    glang == 117 ~ "Thai",
    glang == 118 ~ "Turkish",
    glang == 119 ~ "Ukrainian",
    glang == 120 ~ "Vietnamese",
    glang == 121 ~ "Other",
    TRUE ~ NA_character_  
  ))

#Mapping partner values to a partner column#
data <- data %>%
  mutate(partner = case_when(
    part == 0 ~ "No",
    part == 1 ~ "Yes",
    TRUE ~ NA_character_ 
  ))

#Mapping partner values to a partner column#
data <- data %>%
  mutate(job_yn = case_when(
    job == 0 ~ "No",
    job == 1 ~ "Yes",
    TRUE ~ NA_character_ 
  ))

#Mapping partner values to a partner column#
data <- data %>%
  mutate(job_yn = case_when(
    job == 0 ~ "No",
    job == 1 ~ "Yes",
    TRUE ~ NA_character_ 
  ))

#Mapping health satisfaction values to a satisfaction column#
data <- data %>%
  mutate(health_satisfaction = case_when(
    health == 1 ~ "Very dissatisfied",
    health == 2 ~ "Dissatisfied",
    health == 3 ~ "Neither satisfied nor dissatisfied",
    health == 4 ~ "Satisfied",
    health == 5 ~ "Very satisfied",
    TRUE ~ NA_character_ 
  ))

#Mapping psychotherapy values to a psychotherapy column#
data <- data %>%
  mutate(psyt_yn = case_when(
    psyt == 0 ~ "No",
    psyt == 1 ~ "Yes",
    TRUE ~ NA_character_ 
  ))

```



```{r looking at data types}
str(data)
```

```{r summary statistics for students age}

summary(data$age)

```
```{r finding out how many students there are per year}

academic_year_counts <- data %>%
  group_by(year) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(year)

academic_year_counts$year <- as.factor(academic_year_counts$year)
```

```{r plotting distribution of students across academic years}
ggplot(academic_year_counts, aes(x = year, y = student_count)) +
  geom_col(fill = "blue", alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  labs(title = "Number of students enrolled in each academic year",
       x = "Academic Year",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank()
  ) 

```


```{r finding out the gender split in the data}

sex_counts <- data %>%
  group_by(sex_character) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(sex_character)

sex_counts
```


```{r plotting distribution of students across the sexes}
ggplot(sex_counts, aes(x = fct_reorder(sex_character, student_count, .desc = TRUE), y = student_count, fill = sex_character)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students by Sex",
       x = "Sex",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  # Remove legend if not needed
  )

```

```{r finding out the native languages of the data}

language_counts <- data %>%
  group_by(native_language) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(desc(percentage))

language_counts
```

```{r plotting distribution of students by native language}
ggplot(language_counts, aes(x = fct_reorder(native_language, student_count, .desc = TRUE), y = student_count, fill = native_language)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students for each Native Language",
       x = "Native Language",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1, angle = 45),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  # Remove legend if not needed
  )

```





```{r finding out the partner status of the data}

partner_counts <- data %>%
  group_by(partner) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(desc(percentage))

partner_counts
```


```{r plotting distribution of students by partner status}
ggplot(partner_counts, aes(x = fct_reorder(partner, student_count, .desc = TRUE), y = student_count, fill = partner)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students by Partner Status",
       x = "Has Partner?",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  
  )

```



```{r finding out the job status of the data}

job_counts <- data %>%
  group_by(job_yn) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(desc(percentage))

job_counts
```


```{r plotting distribution of students by job status}
ggplot(job_counts, aes(x = fct_reorder(job_yn, student_count, .desc = TRUE), y = student_count, fill = job_yn)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students by Job Status",
       x = "Has Job?",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  
  )

```



```{r finding out the health satisfaction of the data}

health_satisfaction_counts <- data %>%
  group_by(health_satisfaction) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(desc(percentage))

health_satisfaction_counts
```


```{r plotting distribution of students by health satisfaction}
ggplot(health_satisfaction_counts, aes(x = fct_reorder(health_satisfaction, student_count, .desc = TRUE), y = student_count, fill = health_satisfaction)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students by Health Satisfaction",
       x = "Satisfied with Health?",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1, angle = 45),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  
  )

```


```{r finding out the psychotherapy usage of the data}

pyschotherapy_counts <- data %>%
  group_by(psyt_yn) %>%
  summarise(student_count = n()) %>%
  mutate(percentage = (student_count / sum(student_count)) * 100) %>%
  arrange(desc(percentage))

pyschotherapy_counts
```

```{r plotting distribution of students by psychotherapy usage}
ggplot(pyschotherapy_counts, aes(x = fct_reorder(psyt_yn, student_count, .desc = TRUE), y = student_count, fill = psyt_yn)) +
  geom_col(alpha = 0.8) +
  geom_text(aes(label = student_count), vjust = -0.5, size = 3.5, color = "darkblue") +
  scale_y_continuous(labels = comma) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Number of students by Psychotherapy Usage",
       x = "Psychotherapy Usage in last 12 Months?",
       y = "Number of Students") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1),
    panel.grid.major = element_line(size = 0.1, linetype = 'dotted'),
    panel.grid.minor = element_blank(),
    legend.position = "none"  
  )

```

```{r}
numerical_indices <- c(2,8,11,12,13,14,15,16,17,18,19,20)

ggpairs(data, columns = numerical_indices)
```


```{r}
data$sex_character <- as.factor(data$sex_character)

data$native_language <- as.factor(data$native_language)

data$partner <- as.factor(data$partner)

data$job_yn <- as.factor(data$job_yn)

data$health_satisfaction <- as.factor(data$health_satisfaction)

data$psyt_yn <- as.factor(data$psyt_yn)

```



```{r model evaluation function}
model_evaluation <- function(model, test_sample, truth, categorical = TRUE) {
  yhat <- predict(model, test_sample)
  score <- sum(yhat == truth) / length(truth)
  text <- sprintf("Accuracy score for the model: %.2f%%", score * 100)
  
  if (categorical) {
    cm <- confusionMatrix(yhat, truth)
    print(cm)
    heatmap_data <- as.data.frame(cm$table)
    colnames(heatmap_data) <- c("Predicted", "Actual", "Freq")
    
    ggplot(heatmap_data, aes(x = Predicted, y = Actual, fill = Freq)) +
      geom_tile() +
      geom_text(aes(label = Freq), color = "white") +
      labs(title = text, fill = "Count") +
      theme_minimal()
    
  } else {
    test_sample$predicted <- yhat
    print(text)
    ggpairs(test_sample, aes(color = as.factor(predicted)))
  }
}

```

```{r}
# Select columns for X and y
temp <- c(2,3,8,11:20,22:25,27)
X <- data[, temp]
y <- data$health_satisfaction


# Split data into training and testing sets
set.seed(42)
trainIndex <- createDataPartition(y, p = 0.8, list = FALSE)
X_train <- X[trainIndex, ]
X_test <- X[-trainIndex, ]
y_train <- y[trainIndex]
y_test <- y[-trainIndex]

# Train a Random Forest model
set.seed(0)
forest <- randomForest(X_train, y_train)

# Calculate feature importances
importances <- importance(forest)
forest_importances <- data.frame(Feature = rownames(importances),
                                 Importance = importances)

std <- apply(importances, 2, sd)

forest_importances$Std <- std

# Plot the feature importances with error bars
ggplot(forest_importances, aes(x = reorder(Feature, MeanDecreaseGini), y = MeanDecreaseGini)) +
  geom_bar(stat = "identity", fill = "blue", alpha = 0.8) +
  geom_errorbar(aes(ymin = MeanDecreaseGini - Std, ymax = MeanDecreaseGini + Std), width = 0.2) +
  coord_flip() +
  labs(title = "Feature Importances using MDI",
       x = "Features",
       y = "Mean Decrease in Impurity") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(hjust = 1)
  )
```

